---
title: "How to write a data analysis plan"
author: "Steve Simon"
date: "2018/04/04"
output:
  xaringan::moon_reader:
    self_contained: true
---

## Who is this guy talking to you?

- Steve Simon
- Department of Biomedical and Health Informatics, UMKC
- Enterprise Analytics, KUMC
- P.Mean Consulting

I have helped hundreds of researchers write grants. Most of the assistance was on very small grants ($25,000 or less). Many of the interactions were brief, but some were quite intense.

I've been funded on a half dozen big grants, but never as a principal investigator.

---
## Who is this guy talking to you, continued.

I have co-taught short courses at the 2012 and 2014 International Conference on Integrative Medicine and Health on how to write a CAM grant.

I have attended dozens of continuing education opportunities on grant writing.

---
## Research story

I was working with a colleague in the federal government who wanted some advice about a statistical approach that his collaborators at a different federal agency had proposed. He warned me that his collaborators were insisting on their method because it was delivered by their "statistical gods."

At first, I was jealous. If people thought of me as a god, as someone with supernatural power, then I could probably double my consulting rate. I think that a statistical god could get at least $250 an hour, don't you?

But then it bothered me a bit.

## Research story, continued

How did I learn all of the Statistics that I know? It wasn't delivered on stone tablets and it did not come in a vision. I learned statistics the old fashioned way, by reading books and attending classes and (more recently) through continuing education.

There's nothing supernatural about Statistics. It takes work, but no more work than anything else.

So don't think about statistics as if it were some supernatural power that is beyond the reach of ordinary mortals like yourself. 

